title: Google Associate Cloud Engineer Certification Dump
description: Google's Associate Cloud Engineer (ACE) certification exam question dump
image: https://raw.githubusercontent.com/ghodei/ACE-dump/main/assets/images/favicon.png
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
utterances:
  repo: "https://github.com/ghodei/ACE"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-dark"
theme: jekyll-theme-hacker
